spring:

  datasource:
      url: jdbc:mysql://192.168.5.60:3306/huasheng?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
      username: zzw
      password: zxczxc
      driver-class-name: com.mysql.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      #  Hikari will use the above plus the following to setup connection pooling
      hikari:
        minimum-idle: 5
        maximum-pool-size: 15
        auto-commit: true
        idle-timeout: 30000
        pool-name: DatebookHikariCP
        max-lifetime: 1800000
        connection-timeout: 30000
        connection-test-query: SELECT 1
server:
  port: 7000
